---
title: SP3 Build on OCI
description: Deployment of base SP3 cluster on OCI
schemaVersion: 1.1.0
version: "20210315"
logoUrl: >
  https://objectstorage.uk-london-1.oraclecloud.com/p/gcJUrJ8giUwk_51hi_nTN0Dl66R_7jOOAXU3k3kF-4mOrDCwIoanxChzle0ZAIfm/n/lrbvkel2wjot/b/images/o/mmmlogo_small_130_130.png
locale: "en"
variableGroups:
  - title: "Base configuration"
    variables:
      - ${region}
      - ${compartment_ocid}
      - ${ad}
      - ${ssh_pub_key}
      - ${bastion_image}
      - ${bastion_shape}
      - ${headnode_image}
      - ${headnode_shape}
  - title: "Optional Settings"
    variables:
      - ${env_name}
      - ${name_prefix}
      - ${hn_boot_size}
      - ${hn_data_size}
      - ${hn_work_size}
      - ${show_testing_others}
  - title: "Testing / Other Settings"
    variables:
      - ${bastion_boot_size}
      - ${deploy_test}
    visible: ${show_testing_others}
variables:
  region:
    title: "Region"
    type: oci:identity:region:name
  compartment_ocid:
    title: "Target Compartment"
    type: oci:identity:compartment:id
    required: true
  ad:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Availability Domain"
    title: "Availability Domain"
  ssh_pub_key:
    type: oci:core:ssh:publickey
    title: "Public SSH key"
    required: true
  bastion_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Compute image for the Bastion server"
    title: "Bastion Server Image"
  bastion_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageID: ${bastion_image}
    required: true
    description: "Compute shape for the Bastion server"
    title: "Bastion Server Shape"
  headnode_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Compute image for the Head Node server"
    title: "Head Node Server Image"
  headnode_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageID: ${headnode_image}
    required: true
    description: "Compute shape for the Head Node"
    title: "Head Node Server Shape"
  env_name:
    type: string
    title: "Environment Name"
    description: "Name for the environment - e.g. sp3"
    default: "sp3"
  name_prefix:
    type: string
    title: "Display/Host Name Prefix"
    description: "Optional prefix for all Display Names and Hostnames - letters and digits only"
    pattern: "^[a-zA-Z0-9]+$"
  hn_boot_size:
    type: integer
    title: "Head Node Server Boot Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  hn_data_size:
    type: integer
    title: "Head Node Server Data Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  hn_work_size:
    type: integer
    title: "Head Node Server Work Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  show_testing_others:
    title: "Display all other settings / testing options"
    type: boolean
    default: false
  bastion_boot_size:
    type: integer
    title: "Bastion Server Boot Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  deploy_test:
    type: boolean
    title: Deploy test web server to head node and NFS export (BenH TESTING ONLY)
    default: false
outputs:
  sp3bastionPublicIP:
    title: "Bastion Public IP Address"
    type: copyableString
    visible: true
  sp3headnodePrivateIP:
    title: "Head Node Private IP Address"
    type: copyableString
    visible: true
  sp3_loadbalancer_public_ip:
    visible: false
  sp3_deploy_id:
    title: "Deployment ID"
    type: string
    visible: true
