---
title: SP3 Build
description: SP3 Base Build
schemaVersion: 1.1.0
version: "20210315"
logoUrl: >
  https://cloudmarketplace.oracle.com/marketplace/content?contentId=80357668
locale: "en"
variableGroups:
  - title: "Base configuration"
    variables:
      - ${region}
      - ${compartment_ocid}
      - ${ad}
      - ${ssh_pub_key}
      - ${bastion_shape}
      - ${bastion_image}
      - ${headnode_shape}
      - ${headnode_image}
  - title: "Optional Settings"
    variables:
      - ${env_name}
      - ${name_prefix}
      - ${hn_boot_size}
      - ${hn_data_size}
      - ${hn_work_size}
variables:
  region:
    title: "Region"
    type: oci:identity:region:name
  compartment_ocid:
    title: "Target Compartment"
    type: oci:identity:compartment:id
    required: true
  ad:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Availability Domain"
    title: "Availability Domain"
  ssh_pub_key:
    type: oci:core:ssh:publickey
    title: "Public SSH key"
    required: true
  bastion_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Compute shape for the Bastion server"
    title: "Bastion Server Shape"
  bastion_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Compute image for the Bastion server"
    title: "Bastion Server Image"
  headnode_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Compute shape for the Head Node"
    title: "Head Node Server Shape"
  headnode_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Compute image for the Head Node server"
    title: "Head Node Server Image"
  env_name:
    type: string
    title: "Environment Name"
    description: "Name for the environment - e.g. sp3"
  name_prefix:
    type: string
    title: "Display/Host Name Prefix"
    description: "Optional prefix for all Display Names and Hostnames - letters and digits only"
    pattern: "^[a-zA-Z0-9]+$"
  hn_boot_size:
    type: integer
    title: "Head Node Server Boot Volume Size"
    description: "Size in GB"
  hn_data_size:
    type: integer
    title: "Head Node Server Data Volume Size"
    description: "Size in GB"
  hn_work_size:
    type: integer
    title: "Head Node Server Work Volume Size"
    description: "Size in GB"
