---
title: SP3 Build
description: SP3 Base Build
schemaVersion: 1.1.0
version: "20210315"
logoUrl: >
  https://cloudmarketplace.oracle.com/marketplace/content?contentId=80357668
locale: "en"
variableGroups:
  - title: "Base configuration"
    variables:
      - ${region}
      - ${compartment_ocid}
      - ${ad}
      - ${ssh_pub_key}
      - ${bastion_shape}
      - ${headnode_shape}
  - title: "Optional Settings"
    variables:
      - ${env_name}   
      - ${name_prefix}
variables:
  region:
    title: "Region"
  compartment_ocid:
    title: "Target Compartment"
    type: oci:identity:compartment:id
    required: true
  ad:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Availability Domain"
    title: "Availability Domain"
  ssh_pub_key:
    type: string
    title: "Public SSH key"
    required: true
  bastion_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Compute shape for the Bastion server"
    title: "Bastion Server Shape"
  headnode_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Compute shape for the Head Node"
    title: "Head Node Server Shape"
  env_name:
    type: string
    title: "Environment Name"
    description: "Name for the environment - e.g. sp3"
  name_prefix:
    type: string
    title: "Display/Host Name Prefix"
    description: "Optional prefix for all Display Names and Hostnames"
