---
title: SP3 Build on OCI
description: Deployment of base SP3 cluster on OCI
schemaVersion: 1.1.0
version: "20210315"
logoUrl: >
  https://objectstorage.uk-london-1.oraclecloud.com/p/gcJUrJ8giUwk_51hi_nTN0Dl66R_7jOOAXU3k3kF-4mOrDCwIoanxChzle0ZAIfm/n/lrbvkel2wjot/b/images/o/mmmlogo_small_130_130.png
locale: "en"
variableGroups:
  - title: "Base configuration"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_ocid}
      - ${ad}
      - ${ssh_pub_key}
      - ${bastion_image}
      - ${bastion_shape}
      - ${bastion_ocpus}
      - ${bastion_ram}
      - ${headnode_image}
      - ${headnode_shape}
      - ${headnode_ocpus}
      - ${headnode_ram}
      - ${env_name}
      - ${specify_prefix}
      - ${name_prefix}
  - title: "Optional Settings"
    variables:
      - ${hn_boot_size}
      - ${hn_data_size}
      - ${hn_work_size}
      - ${create_child_comp}
      - ${specify_worker_spec}
      - ${install_nginx}
      - ${create_dns}
      - ${show_testing_others}
  - title: "Worker Node Configurations"
    visible: ${specify_worker_spec}
    variables:
      - ${worker_image}
      - ${worker_shape}
      - ${worker_ocpus}
      - ${worker_ram}
      - ${worker_use_scratch}
  - title: "Testing / Other Settings"
    variables:
      - ${bastion_boot_size}
      - ${deploy_test}
    visible: ${show_testing_others}
variables:
  tenancy_ocid:
    visible: false
  region:
    title: "Region"
    type: oci:identity:region:name
  compartment_ocid:
    title: "Target Compartment"
    type: oci:identity:compartment:id
    required: true
  ad:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Availability Domain"
    title: "Availability Domain"
  ssh_pub_key:
    type: oci:core:ssh:publickey
    title: "Public SSH key"
    required: true
  bastion_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Compute image for the Bastion server"
    title: "Bastion Server Image"
  bastion_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageID: ${bastion_image}
    required: true
    description: "Compute shape for the Bastion server"
    title: "Bastion Server Shape"
  bastion_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    required: true
    title: "Bastion number of CPUs (cores)"
    description: "You can customize the number of CPU cores to a flexible shape."
    visible:
      and:
        - eq:
          - bastion_shape 
          - "VM.Standard.E3.Flex"
  bastion_ram:
    type: integer
    minimum: 1
    maximum: 1024
    required: true
    title: "Bastion Server memory (GB)"
    description: "You can customize the amount of memory allocated to a flexible shape."
    visible:
      and:
        - eq:
          - bastion_shape 
          - "VM.Standard.E3.Flex"
  headnode_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Compute image for the Head Node server"
    title: "Head Node Server Image"
  headnode_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageID: ${headnode_image}
    required: true
    description: "Compute shape for the Head Node"
    title: "Head Node Server Shape"
  headnode_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    required: true
    title: "Head Node number of CPUs (cores)"
    description: "You can customize the number of CPU cores to a flexible shape."
    visible:
      and:
        - eq:
          - headnode_shape 
          - "VM.Standard.E3.Flex"
  headnode_ram:
    type: integer
    minimum: 1
    maximum: 1024
    required: true
    title: "Head Node memory (GB)"
    description: "You can customize the amount of memory allocated to a flexible shape."
    visible:
      and:
        - eq:
          - headnode_shape 
          - "VM.Standard.E3.Flex"
  env_name:
    type: string
    title: "Environment Name"
    description: "Name for the environment - e.g. sp3 - lower case and digits only - must start with lower case letter"
    pattern: "^[a-z][a-z0-9]+$"
    default: "sp3"
    required: true
  specify_prefix:
    title: "Would you like to specify a prefix for the deployment?"
    type: boolean
    default: false
  name_prefix:
    type: string
    title: "Display/Host Name Prefix"
    description: "Optional prefix for all Display Names and Hostnames - lower case and digits only - must start with lower case letter"
    pattern: "^[a-z][a-z0-9]+$"
    visible: ${specify_prefix}
  hn_boot_size:
    type: integer
    title: "Head Node Server Boot Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  hn_data_size:
    type: integer
    title: "Head Node Server Data Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  hn_work_size:
    type: integer
    title: "Head Node Server Work Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  create_child_comp:
    title: "Create a child compartment for the stack"
    type: boolean
  specify_worker_spec:
    title: "Specify Worker Node settings?"
    type: boolean
    default: false
  install_nginx:
    title: "Install nginx for testing?"
    type: boolean
    default: false
  create_dns:
    title: "Create DNS record in oci.sp3dev.ml?"
    type: boolean
    default: false
  show_testing_others:
    title: "Display all other settings / testing options?"
    type: boolean
    default: false
  bastion_boot_size:
    type: integer
    title: "Bastion Server Boot Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  deploy_test:
    visible: false
  worker_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Compute image for the Worker Nodes"
    title: "Worker Nodes Image"
  worker_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageID: ${worker_image}
    required: true
    description: "Compute shape for the Worker Node"
    title: "Worker Node Server Shape"
  worker_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    required: true
    title: "Worker Node number of CPUs (cores)"
    description: "You can customize the number of CPU cores to a flexible shape."
    visible:
      and:
        - eq:
          - worker_shape 
          - "VM.Standard.E3.Flex"
  worker_ram:
    type: integer
    minimum: 1
    maximum: 1024
    required: true
    title: "Worker Node memory (GB)"
    description: "You can customize the amount of memory allocated to a flexible shape."
    visible:
      and:
        - eq:
          - worker_shape 
          - "VM.Standard.E3.Flex"
  worker_use_scratch:
    title: "Worker Node use local scratch storage - choose DenseIO shape"
    type: boolean
    default: false    
outputs:
  sp3bastionPublicIP:
    title: "Bastion Public IP Address"
    type: copyableString
    visible: true
  sp3headnodePrivateIP:
    title: "Head Node Private IP Address"
    type: copyableString
    visible: true
  sp3_loadbalancer_public_ip:
    visible: false
  sp3_deploy_id:
    title: "Deployment ID"
    type: string
    visible: true
  sp3_loadbalancer_url:
    title: "Load Balancer URL"
    type: link
    visible: true
