sp3_file_store:
  install: true
  nfs:
    volumn_name: nextflow-fss-storage
    pv_size_data: 100Gi
    pv_size_work: 100Gi
    pvc_size_data: 50Gi
    pvc_size_work: 50Gi

rbac:
  install: true

test:
  install: true
  deploymentImageName: lhr.ocir.io/lrbvkel2wjot/nftest
  deploymentImageTag: latest
  pullSecretName: sp3dockersecret
  nfs:
    volumn_name: nextflow-fss-storage


