apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanup-pods
spec:
  schedule: "0 0 * * 0"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
          - name: kubectl-runner
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command: ["sh", "-c", "kubectl get pods --namespace default  --no-headers=true | grep -e Error -e Completed | \
                      awk 'match ($5,/[3-9]d*$|[0-9][0-9]d*$|[0-9][0-9][0-9]d*$/){print $1}' | xargs -r kubectl --namespace default delete pod"]
          restartPolicy: Never
